
import com.sun.speech.freetts.Voice;
import com.sun.speech.freetts.VoiceManager;
import java.util.*;
import java.io.*;
import java.nio.file.Files; 
import java.nio.file.Paths;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author huanc_9jkjulx
 */
public class NewJFrame extends javax.swing.JFrame  {

    /**
     * Creates new form NewJFrame
     */
    DictionaryCommanline test = new DictionaryCommanline();
    public NewJFrame() throws SQLException, ClassNotFoundException{
        initComponents();
        
        try{
            test.insertFromFileAuto();
            test.insertFromDataBase();
        } catch(IOException e){
            System.out.print("ERORR");
        }  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuRight = new javax.swing.JPopupMenu();
        sua = new javax.swing.JMenuItem();
        xoa = new javax.swing.JMenuItem();
        jDialog1 = new javax.swing.JDialog();
        menuRight2 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        screen = new javax.swing.JPanel();
        screen1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        start = new javax.swing.JButton();
        start2 = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        info = new javax.swing.JButton();
        screen2 = new javax.swing.JPanel();
        search = new javax.swing.JTextField();
        searchbtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        wordMea = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        wordSea = new javax.swing.JList<>();
        voice = new javax.swing.JButton();
        back = new javax.swing.JButton();
        addWordbtn = new javax.swing.JButton();
        updatebtn = new javax.swing.JButton();
        screen3 = new javax.swing.JPanel();
        search1 = new javax.swing.JTextField();
        searchbtn1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        wordMea1 = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        wordSea1 = new javax.swing.JList<>();
        voice1 = new javax.swing.JButton();
        back1 = new javax.swing.JButton();
        addWord1 = new javax.swing.JButton();
        updatebtn1 = new javax.swing.JButton();
        screen5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        sua.setText("Sửa");
        sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suaActionPerformed(evt);
            }
        });
        menuRight.add(sua);

        xoa.setText("Xóa");
        xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xoaActionPerformed(evt);
            }
        });
        menuRight.add(xoa);

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jMenuItem1.setText("Sửa");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuRight2.add(jMenuItem1);

        jMenuItem2.setText("Xóa");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        menuRight2.add(jMenuItem2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dictionary 2.0");
        getContentPane().setLayout(new java.awt.CardLayout());

        screen.setLayout(new java.awt.CardLayout());

        screen1.setBackground(new java.awt.Color(102, 255, 204));

        jLabel1.setFont(new java.awt.Font("Trajan Pro", 1, 24)); // NOI18N
        jLabel1.setText("    Dictionary 2.0");

        start.setText("Từ điển Anh-Việt");
        start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startActionPerformed(evt);
            }
        });

        start2.setText("Từ điển Anh-Anh");
        start2.setActionCommand("");
        start2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                start2ActionPerformed(evt);
            }
        });

        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        info.setText("Thông tin");
        info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout screen1Layout = new javax.swing.GroupLayout(screen1);
        screen1.setLayout(screen1Layout);
        screen1Layout.setHorizontalGroup(
            screen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(screen1Layout.createSequentialGroup()
                .addGroup(screen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(screen1Layout.createSequentialGroup()
                        .addGap(264, 264, 264)
                        .addGroup(screen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(info, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(start2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(start, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(screen1Layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(254, Short.MAX_VALUE))
        );
        screen1Layout.setVerticalGroup(
            screen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(screen1Layout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(start)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(start2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(info)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exit)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        screen.add(screen1, "card3");
        screen1.getAccessibleContext().setAccessibleName("screen1");

        screen2.setBackground(new java.awt.Color(0, 153, 153));

        search.setText("Nhập vào từ cần tìm");
        search.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                searchFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                searchFocusLost(evt);
            }
        });
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        searchbtn.setText("Search");
        searchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbtnActionPerformed(evt);
            }
        });

        wordMea.setColumns(20);
        wordMea.setRows(5);
        jScrollPane2.setViewportView(wordMea);

        wordSea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                wordSeaMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                wordSeaMouseReleased(evt);
            }
        });
        jScrollPane4.setViewportView(wordSea);

        voice.setText("Voice");
        voice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                voiceMouseReleased(evt);
            }
        });
        voice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voiceActionPerformed(evt);
            }
        });

        back.setText("Quay lại");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        addWordbtn.setText("Thêm từ");
        addWordbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addWordbtnActionPerformed(evt);
            }
        });

        updatebtn.setText("Cập nhật");
        updatebtn.setActionCommand("");
        updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout screen2Layout = new javax.swing.GroupLayout(screen2);
        screen2.setLayout(screen2Layout);
        screen2Layout.setHorizontalGroup(
            screen2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(screen2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(screen2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(screen2Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(screen2Layout.createSequentialGroup()
                        .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchbtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(voice)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addWordbtn)
                        .addGap(32, 32, 32)
                        .addComponent(updatebtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                        .addComponent(back)))
                .addContainerGap())
        );
        screen2Layout.setVerticalGroup(
            screen2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(screen2Layout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addGroup(screen2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(voice, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addWordbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updatebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(screen2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        screen.add(screen2, "card4");

        screen3.setBackground(new java.awt.Color(255, 204, 255));

        search1.setText("Nhập vào từ cần tìm");
        search1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                search1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                search1FocusLost(evt);
            }
        });
        search1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search1ActionPerformed(evt);
            }
        });

        searchbtn1.setText("Search");
        searchbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbtn1ActionPerformed(evt);
            }
        });

        wordMea1.setColumns(20);
        wordMea1.setRows(5);
        jScrollPane3.setViewportView(wordMea1);

        wordSea1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                wordSea1MouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                wordSea1MouseReleased(evt);
            }
        });
        wordSea1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                wordSea1ComponentShown(evt);
            }
        });
        jScrollPane5.setViewportView(wordSea1);

        voice1.setText("Voice");
        voice1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                voice1MouseReleased(evt);
            }
        });
        voice1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voice1ActionPerformed(evt);
            }
        });

        back1.setText("Quay lại");
        back1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back1ActionPerformed(evt);
            }
        });

        addWord1.setText("Thêm từ");
        addWord1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addWord1ActionPerformed(evt);
            }
        });

        updatebtn1.setText("Cập nhật");
        updatebtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout screen3Layout = new javax.swing.GroupLayout(screen3);
        screen3.setLayout(screen3Layout);
        screen3Layout.setHorizontalGroup(
            screen3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(screen3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(screen3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(screen3Layout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(screen3Layout.createSequentialGroup()
                        .addComponent(search1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchbtn1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(voice1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addWord1)
                        .addGap(32, 32, 32)
                        .addComponent(updatebtn1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                        .addComponent(back1)))
                .addContainerGap())
        );
        screen3Layout.setVerticalGroup(
            screen3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(screen3Layout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addGroup(screen3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(search1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(voice1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(back1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addWord1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updatebtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(screen3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        screen.add(screen3, "card5");

        screen5.setBackground(new java.awt.Color(255, 255, 0));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Từ điển Anh-Anh có sử dụng bảng entries trong sakila (database trong mySql)\nĐược kết nối với database thông qua tài khoản : root , mật khẩu: 341997mok.\n\nTừ điển Anh-Việt sử dụng dữ liệu từ file dictionaries.txt\n\nPhần mềm được tích hợp giọng nói.  ");
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setText("Quay lại");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout screen5Layout = new javax.swing.GroupLayout(screen5);
        screen5.setLayout(screen5Layout);
        screen5Layout.setHorizontalGroup(
            screen5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(screen5Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 663, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, screen5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86))
        );
        screen5Layout.setVerticalGroup(
            screen5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, screen5Layout.createSequentialGroup()
                .addContainerGap(91, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        screen.add(screen5, "card4");

        getContentPane().add(screen, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startActionPerformed
        // TODO add your handling code here:
        screen.removeAll();
        screen.add(screen2);
        screen.repaint();
        screen.revalidate();

        wordSea.setListData(test.getWordTargets());
        
    }//GEN-LAST:event_startActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_searchActionPerformed

    private void searchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbtnActionPerformed
        // TODO add your handling code here:
        String input = search.getText();
        System.out.println(input);

        ArrayList<String> list = test.dictionarySearcher(input);
        String[] temp = new String[500000];
        for (int i = 0;i < list.size() ;++i ) {
            temp[i] = list.get(i);
        }
        wordSea.setListData(temp);

        
        //
    }//GEN-LAST:event_searchbtnActionPerformed

    private void wordSeaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wordSeaMouseClicked
        // TODO add your handling code here:
        String word_target = "";
        
        if(wordSea.getSelectedIndex() != -1){
            word_target = wordSea.getSelectedValue();
        }
        System.out.println(word_target);
        word_target = word_target + "\n\n" + test.dictionaryLookup(word_target,test.getListWord()) ;
        wordMea.setText(word_target);
    }//GEN-LAST:event_wordSeaMouseClicked

    private void searchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchFocusGained
        // TODO add your handling code here:
        if(search.getText().equals("Nhập vào từ cần tìm")){
            search.setText("");
        }
    }//GEN-LAST:event_searchFocusGained

    private void searchFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchFocusLost
        // TODO add your handling code here:
         if(search.getText().equals("")){
            search.setText("Nhập vào từ cần tìm");
            wordSea.setListData(test.getWordTargets());
        }
    }//GEN-LAST:event_searchFocusLost

    private void voiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voiceActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_voiceActionPerformed

    private void voiceMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_voiceMouseReleased
        // TODO add your handling code here:
        String speakWord = wordMea.getText();
        int len = 0;
        for(int i = 0; i < speakWord.length() ; ++i){
            if(speakWord.charAt(i) == '\n'){
                len = i;
                break;
            }
        }
        speakWord = speakWord.substring(0,len);
        System.out.println(speakWord);
        System.setProperty("mbrola.base","mbrola");

        VoiceManager vm = VoiceManager.getInstance();
        Voice v = vm.getVoice("mbrola_us2");
        v.allocate();
        v.speak(speakWord);
    }//GEN-LAST:event_voiceMouseReleased

    private void start2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_start2ActionPerformed
        // TODO add your handling code here:
        screen.removeAll();
        screen.add(screen3);
        screen.repaint();
        screen.revalidate();

        wordSea1.setListData(test.getWordTargets2());
    }//GEN-LAST:event_start2ActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_exitActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        screen.removeAll();
        screen.add(screen1);
        screen.repaint();
        screen.revalidate();
    }//GEN-LAST:event_backActionPerformed

    private void addWordbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addWordbtnActionPerformed
        // TODO add your handling code here:
         String input1 = JOptionPane.showInputDialog(this,"Từ mới ");
        String input2 = JOptionPane.showInputDialog(this,"Nghĩa ");
        test.insertFromCommanline(input1,input2,test.getListWord());
        JOptionPane.showMessageDialog(this, "Đã nhập thành công");
        
    }//GEN-LAST:event_addWordbtnActionPerformed

    private void search1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_search1FocusGained
        // TODO add your handling code here:
        if(search1.getText().equals("Nhập vào từ cần tìm")){
            search1.setText("");
        }
    }//GEN-LAST:event_search1FocusGained

    private void search1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_search1FocusLost
        // TODO add your handling code here:
          if(search1.getText().equals("")){
            search1.setText("Nhập vào từ cần tìm");
            wordSea1.setListData(test.getWordTargets2());
        }
    }//GEN-LAST:event_search1FocusLost

    private void search1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search1ActionPerformed

    private void searchbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbtn1ActionPerformed
        // TODO add your handling code here:
        String input = search1.getText();
        System.out.println(input);

        ArrayList<String> list = test.dictionarySearcher2(input);
        String[] temp = new String[500000];
        for (int i = 0;i < list.size() ;++i ) {
            temp[i] = list.get(i);
        }
        wordSea1.setListData(temp);
    }//GEN-LAST:event_searchbtn1ActionPerformed

    private void wordSea1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wordSea1MouseClicked
        // TODO add your handling code here:
        String word_target = "";
        
        if(wordSea1.getSelectedIndex() != -1){
            word_target = wordSea1.getSelectedValue();
        }
        System.out.println(word_target);
        word_target = word_target + "\n\n" + test.dictionaryLookup(word_target,test.getListWord2()) ;
        wordMea1.setText(word_target);
    }//GEN-LAST:event_wordSea1MouseClicked

    private void voice1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_voice1MouseReleased
        // TODO add your handling code here:
        String speakWord = wordMea1.getText();
        int len = 0;
        for(int i = 0; i < speakWord.length() ; ++i){
            if(speakWord.charAt(i) == '\n'){
                len = i;
                break;
            }
        }
        speakWord = speakWord.substring(0,len);
        System.out.println(speakWord);
        System.setProperty("mbrola.base","mbrola");

        VoiceManager vm = VoiceManager.getInstance();
        Voice v = vm.getVoice("mbrola_us2");
        v.allocate();
        v.speak(speakWord);
    }//GEN-LAST:event_voice1MouseReleased

    private void voice1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voice1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_voice1ActionPerformed

    private void back1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back1ActionPerformed
        // TODO add your handling code here:
        screen.removeAll();
        screen.add(screen1);
        screen.repaint();
        screen.revalidate();
    }//GEN-LAST:event_back1ActionPerformed

    private void addWord1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addWord1ActionPerformed
        // TODO add your handling code here:
        String input1 = JOptionPane.showInputDialog(this,"Từ mới ");
        String input2 = JOptionPane.showInputDialog(this,"Nghĩa ");
        test.insertFromCommanline(input1,input2,test.getListWord2());
        JOptionPane.showMessageDialog(this, "Đã nhập thành công");
    }//GEN-LAST:event_addWord1ActionPerformed

    private void wordSea1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_wordSea1ComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_wordSea1ComponentShown

    private void wordSea1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wordSea1MouseReleased
        // TODO add your handling code here:
        if(evt.isPopupTrigger()){
            menuRight2.show(this,evt.getX()+45,evt.getY()+155);
        }
    }//GEN-LAST:event_wordSea1MouseReleased

    private void xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xoaActionPerformed
        // TODO add your handling code here:
        String speakWord = wordMea.getText();
        int len = 0;
        for(int i = 0; i < speakWord.length() ; ++i){
            if(speakWord.charAt(i) == '\n'){
                len = i;
                break;
            }
        }
        speakWord = speakWord.substring(0,len);
        System.out.println(speakWord);
        test.dictionaryDelete(speakWord, test.getListWord());
        
        String input = search.getText();
        System.out.println(input);

        ArrayList<String> list = test.dictionarySearcher(input);
        String[] temp = new String[500000];
        for (int i = 0;i < list.size() ;++i ) {
            temp[i] = list.get(i);
        }
        wordSea.setListData(temp);
        if(input.equals("Nhập vào từ cần tìm")){
            wordSea.setListData(test.getWordTargets());
        }
    }//GEN-LAST:event_xoaActionPerformed

    private void suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suaActionPerformed
        // TODO add your handling code here:
        String speakWord = wordMea.getText();
        int len = 0;
        for(int i = 0; i < speakWord.length() ; ++i){
            if(speakWord.charAt(i) == '\n'){
                len = i;
                break;
            }
        }
        speakWord = speakWord.substring(0,len);
        System.out.println(speakWord);
        String word_fix = JOptionPane.showInputDialog(this,"Sửa thành ");
        test.dictionaryFix(speakWord, word_fix, test.getListWord());
        
        String input = search.getText();
        System.out.println(input);

        ArrayList<String> list = test.dictionarySearcher(input);
        String[] temp = new String[500000];
        for (int i = 0;i < list.size() ;++i ) {
            temp[i] = list.get(i);
        }
        wordSea.setListData(temp);
    }//GEN-LAST:event_suaActionPerformed

    private void wordSeaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wordSeaMouseReleased
        // TODO add your handling code here:
        if(evt.isPopupTrigger()){
            menuRight.show(this,evt.getX()+45,evt.getY()+155);
        }
    }//GEN-LAST:event_wordSeaMouseReleased

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        String speakWord = wordMea1.getText();
        int len = 0;
        for(int i = 0; i < speakWord.length() ; ++i){
            if(speakWord.charAt(i) == '\n'){
                len = i;
                break;
            }
        }
        speakWord = speakWord.substring(0,len);
        System.out.println(speakWord);
        String word_fix = JOptionPane.showInputDialog(this,"Sửa thành ");
        test.dictionaryFix(speakWord, word_fix, test.getListWord2());
        
        String input = search1.getText();
        System.out.println(input);

        ArrayList<String> list = test.dictionarySearcher2(input);
        String[] temp = new String[500000];
        for (int i = 0;i < list.size() ;++i ) {
            temp[i] = list.get(i);
        }
        wordSea1.setListData(temp);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        String speakWord = wordMea1.getText();
        int len = 0;
        for(int i = 0; i < speakWord.length() ; ++i){
            if(speakWord.charAt(i) == '\n'){
                len = i;
                break;
            }
        }
        speakWord = speakWord.substring(0,len);
        System.out.println(speakWord);
        test.dictionaryDelete(speakWord, test.getListWord2());
        
        String input = search1.getText();
        System.out.println(input);

        ArrayList<String> list = test.dictionarySearcher2(input);
        String[] temp = new String[500000];
        for (int i = 0;i < list.size() ;++i ) {
            temp[i] = list.get(i);
        }
        wordSea1.setListData(temp);
        if(input.equals("Nhập vào từ cần tìm")){
            wordSea1.setListData(test.getWordTargets2());
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void updatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebtnActionPerformed
        // TODO add your handling code here:
        test.dictionaryUpdate(test.getListWord());
        JOptionPane.showMessageDialog(this, "Cập nhật thành công");
    }//GEN-LAST:event_updatebtnActionPerformed

    private void updatebtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebtn1ActionPerformed
        // TODO add your handling code here:
        
        JOptionPane.showMessageDialog(this, "Chức năng sẽ được mở ở phiên bản kết tiếp :)");
    }//GEN-LAST:event_updatebtn1ActionPerformed

    private void infoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoActionPerformed
        // TODO add your handling code here:
        screen.removeAll();
        screen.add(screen5);
        screen.repaint();
        screen.revalidate();
    }//GEN-LAST:event_infoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        screen.removeAll();
        screen.add(screen1);
        screen.repaint();
        screen.revalidate();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
           
            public void run() {
                try {
                    new NewJFrame().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addWord1;
    private javax.swing.JButton addWordbtn;
    private javax.swing.JButton back;
    private javax.swing.JButton back1;
    private javax.swing.JButton exit;
    private javax.swing.JButton info;
    private javax.swing.JButton jButton1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPopupMenu menuRight;
    private javax.swing.JPopupMenu menuRight2;
    private javax.swing.JPanel screen;
    private javax.swing.JPanel screen1;
    private javax.swing.JPanel screen2;
    private javax.swing.JPanel screen3;
    private javax.swing.JPanel screen5;
    private javax.swing.JTextField search;
    private javax.swing.JTextField search1;
    private javax.swing.JButton searchbtn;
    private javax.swing.JButton searchbtn1;
    private javax.swing.JButton start;
    private javax.swing.JButton start2;
    private javax.swing.JMenuItem sua;
    private javax.swing.JButton updatebtn;
    private javax.swing.JButton updatebtn1;
    private javax.swing.JButton voice;
    private javax.swing.JButton voice1;
    private javax.swing.JTextArea wordMea;
    private javax.swing.JTextArea wordMea1;
    private javax.swing.JList<String> wordSea;
    private javax.swing.JList<String> wordSea1;
    private javax.swing.JMenuItem xoa;
    // End of variables declaration//GEN-END:variables
}
